stages:
  - build
  - test
  - deploy

variables:
  SSH_HOST: "172.31.89.152"
  SSH_USER: "it_is_me"
  DEPLOY_DIR: "/opt/mule-apps"
  JAR_NAME: "message-connector.jar"

before_script:
  - export PATH=$PATH:/opt/maven/bin

build:
  stage: build
  image: maven:3.8.7-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

test:
  stage: test
  image: maven:3.8.7-openjdk-17
  script:
    - mvn test
  only:
    - main

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client
  script:
    - scp target/*.jar $SSH_USER@$SSH_HOST:$DEPLOY_DIR/$JAR_NAME
    - ssh $SSH_USER@$SSH_HOST "cd $DEPLOY_DIR && nohup java -jar $JAR_NAME > app.log 2>&1 &"
  only:
    - main
  dependencies:
    - build
