middleware:
  message_processing:
    message_limit: '4'

  timeouts:
    main_for_each: '180000'

  scheduler:
    frequency: '30000'
    start_delay: '0'
    
  postgres:
    common:
      host: 'localhost'
      port: '5432'
      username: 'postgres'
      password: '12345'
    esb:
      database: 'esb'
      host: '${middleware.postgres.common.host}'
      port: '${middleware.postgres.common.port}'
      username: '${middleware.postgres.common.username}'
      password: '${middleware.postgres.common.password}'
      url: 'jdbc:postgresql://${middleware.postgres.esb.host}:${middleware.postgres.esb.port}/${middleware.postgres.esb.database}' 
    msg:
      database: 'msg'
      host: '${middleware.postgres.common.host}'
      port: '${middleware.postgres.common.port}'
      username: '${middleware.postgres.common.username}'
      password: '${middleware.postgres.common.password}'
      url: 'jdbc:postgresql://${middleware.postgres.msg.host}:${middleware.postgres.msg.port}/${middleware.postgres.msg.database}'
      
  http:
    common:
      host: 'localhost'
      port: '8081'
      path: ''
    test:
      host: '${middleware.http.common.host}'
      port: '${middleware.http.common.port}'
      path: '${middleware.http.common.path}/test'
      url: '${middleware.http.common.host}:${middleware.http.common.port}${middleware.http.common.path}/test'